#### This notebook is to rank differentials for sleep measurements

In [1]:
import pandas as pd
import numpy as np

In [2]:
tax = pd.read_csv('taxonomy-table/taxonomy.tsv', sep='\t', header=0)
tax.head()

,Feature ID,Taxon
0,TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...
1,TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCA...,k__Bacteria; p__Proteobacteria; c__Gammaproteo...
2,TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...
3,TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...
4,AACGTAGGTCACAAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...

In [3]:
df = pd.read_csv('Songbird/amplitute-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['AMAMPT'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'AMAMPT']]
df

,Feature ID,Taxon,AMAMPT
0,TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-0.524
929,TACGTAGGGGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGTG...,k__Bacteria; p__Tenericutes; c__Mollicutes; o_...,-0.174
1248,TACGTATGTCGCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGCG...,k__Bacteria; p__Fusobacteria; c__Fusobacteriia...,-0.087
1328,TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-0.053
775,TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-0.053
844,TACGGAGGATCCGAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-0.051
594,TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-0.050
243,TACGGAGGATTCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-0.050
994,TACGTAGGGGGCAAGCGTTATCCGGAATTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.045
1091,TACGTAGGGCGCGAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCT...,k__Bacteria; p__Actinobacteria; c__Actinobacte...,-0.045

In [4]:
df.to_csv('amplitute.csv')

In [5]:
df = pd.read_csv('Songbird/amplitute-cat-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['AMAMPT_C1'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'AMAMPT_C1']]
df.to_csv('amplitute-cat.csv')
df.head()

,Feature ID,Taxon,AMAMPT_C1
851,TACGGAGGATCCAAGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-6.164
243,TACGGAGGATTCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-4.121
1248,TACGTATGTCGCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGCG...,k__Bacteria; p__Fusobacteria; c__Fusobacteriia...,-4.116
1328,TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-3.956
503,TACGTAGGGGGCGAGCGTTGTCCGGAATGACTGGGCGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-3.658

In [6]:
df = pd.read_csv('Songbird/Acrophase-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['AMPHIT'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'AMPHIT']]
df.to_csv('Acrophase.csv')
df.head()

,Feature ID,Taxon,AMPHIT
984,TACGTAGGGGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGTG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-2.805
1181,TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-1.744
858,TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-1.474
511,TACGTAGGGGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGTG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-1.254
1345,TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,1.169

In [7]:
df = pd.read_csv('Songbird/AcrophaseSD-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['AMPHIT_15SD'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'AMPHIT_15SD']]
df.to_csv('AcrophaseSD.csv')
df.head()

,Feature ID,Taxon,AMPHIT_15SD
14,TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCA...,k__Bacteria; p__Proteobacteria; c__Gammaproteo...,-4.423
503,TACGTAGGGGGCGAGCGTTGTCCGGAATGACTGGGCGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,4.150
1040,TACGTAGGTGGCGAGCGTTATCCGGAATCATTGGGCGTAAAGGGTG...,k__Bacteria; p__Firmicutes; c__Erysipelotrichi...,4.102
1054,TACGTATGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-3.866
957,TACGTATGGAGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,3.593

In [8]:
df = pd.read_csv('Songbird/Fstats-cat-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['AMFVT_C1'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'AMFVT_C1']]
df.to_csv('Fstats-cat.csv')
df.head()

,Feature ID,Taxon,AMFVT_C1
130,TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCA...,k__Bacteria; p__Proteobacteria; c__Gammaproteo...,-3.767
1219,TACGTAGGGAGCGAGCGTTATCCGGAATTATTGGGTGTAAAGGGTG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-3.705
503,TACGTAGGGGGCGAGCGTTGTCCGGAATGACTGGGCGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-3.564
749,TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,3.140
267,TACGGAGGGTGCAAGCGTTGTCCGGAATCATTGGGCGTAAAGAGTT...,k__Bacteria; p__Cyanobacteria; c__4C0d-2; o__Y...,-3.098

In [9]:
df = pd.read_csv('Songbird/Fstats-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['AMFVT'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'AMFVT']]
df.to_csv('Fstats.csv')
df.head()

,Feature ID,Taxon,AMFVT
0,TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-1.068
848,TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-0.247
711,TACGTAGGGGGCGAGCGTTGTCCGGATTGACTGGGCGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-0.060
1362,TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,0.027
775,TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-0.016

In [10]:
df = pd.read_csv('Songbird/Poorslp-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['PQBADSLP[T.1: Yes]'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'PQBADSLP[T.1: Yes]']]
df.to_csv('Poorslp.csv')
df.head()

,Feature ID,Taxon,PQBADSLP[T.1: Yes]
554,TACGGAAGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-5.437
929,TACGTAGGGGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGTG...,k__Bacteria; p__Tenericutes; c__Mollicutes; o_...,-4.958
684,TACGGAAGGTCCAGGCGTTATCCGGATTTATTGGGTTTAAAGGGAG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-4.569
1261,TACGTAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTG...,k__Bacteria; p__Proteobacteria; c__Betaproteob...,-4.504
1196,TACGGGGGATGCGAGCGTTATCCGGATTCATTGGGTTTAAAGGGTG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-4.247

In [11]:
df = pd.read_csv('Songbird/Slphours-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['SLEEPHRS[T.3:>=8 HRS]'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'SLEEPHRS[T.3:>=8 HRS]']]
df.to_csv('Slphours.csv')
df.head()

,Feature ID,Taxon,SLEEPHRS[T.3:>=8 HRS]
1270,TACGTAGGTGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGCG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-5.847
1196,TACGGGGGATGCGAGCGTTATCCGGATTCATTGGGTTTAAAGGGTG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-4.363
14,TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCA...,k__Bacteria; p__Proteobacteria; c__Gammaproteo...,-4.196
1357,TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,-3.690
1256,TACGTAGGGAGCAAGCGTTATCCGGATTTATTGGGTGTAAAGGGTG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-3.635

In [12]:
df = pd.read_csv('Songbird/Slphours-con-table/metadata.tsv', sep='\t', header=0)
df = df.drop(df.index[0])
df = pd.merge(df, tax, right_on='Feature ID', left_on = 'featureid', how = 'left')
df = df.drop(columns = 'featureid')
cols = df.columns.drop(['Feature ID','Taxon'])
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df[cols] = df[cols].round(3) 
df = df.iloc[(-df['SLSLPHRS'].abs()).argsort()]
df = df[:10]
df = df[['Feature ID', 'Taxon', 'SLSLPHRS']]
df.to_csv('Slphours-con.csv')
df.head()

,Feature ID,Taxon,SLSLPHRS
1234,TACGGGGGATGCGAGCGTTATCCGGATTCATTGGGTTTAAAGGGTG...,k__Bacteria; p__Bacteroidetes; c__Bacteroidia;...,1.795
845,TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,-1.342
1238,TACGTAGGTGGCGAGCGTTGTTCGGATTTATTGGGCGTAAAGGGTC...,k__Bacteria; p__Lentisphaerae; c__[Lentisphaer...,1.178
623,TACGTAGGTGGCGAGCGTTATCCGGATTTATTGGGCGTAAAGGGTG...,k__Bacteria; p__Tenericutes; c__Mollicutes; o_...,1.041
694,TACGTAGGGAGCGAGCGTTATCCGGATTTATTGGGTGTAAAGGGTG...,k__Bacteria; p__Firmicutes; c__Clostridia; o__...,1.039